name: mixpanel_flutter
description: Official Flutter Tracking SDK for Mixpanel Analytics developed and maintained by Mixpanel, Inc.
version: 2.4.4
homepage: https://mixpanel.com
repository: https://github.com/mixpanel/mixpanel-flutter
issue_tracker: https://github.com/mixpanel/mixpanel-flutter/issues
documentation: https://developer.mixpanel.com/docs/flutter

environment:
  sdk: '>=3.8.0 <4.0.0'
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  assets:
    - assets/mixpanel.js

  plugin:
    platforms:
      android:
        package: com.mixpanel.mixpanel_flutter
        pluginClass: MixpanelFlutterPlugin
      ios:
        pluginClass: MixpanelFlutterPlugin
      web:
        pluginClass: MixpanelFlutterPlugin
        fileName: mixpanel_flutter_web.dart
