name: mixpanel_flutter
description: Official Flutter Tracking SDK for Mixpanel Analytics developed and maintained by Mixpanel, Inc.
version: 2.1.1
homepage: https://mixpanel.com
repository: https://github.com/mixpanel/mixpanel-flutter
issue_tracker: https://github.com/mixpanel/mixpanel-flutter/issues
documentation: https://developer.mixpanel.com/docs/flutter

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.6.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.5

flutter:
  assets:
    - assets/mixpanel.js

  plugin:
    platforms:
      android:
        package: com.mixpanel.mixpanel_flutter
        pluginClass: MixpanelFlutterPlugin
      ios:
        pluginClass: MixpanelFlutterPlugin
      web:
        pluginClass: MixpanelFlutterPlugin
        fileName: mixpanel_flutter_web.dart
